version: '3'

networks:
  network-lara-ecommerce:

services:
  nginx:
    image: nginx:1.18.0-alpine
    container_name: nginx-lara-ecommerce
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - network-lara-ecommerce
  php:
    build: docker/php-fpm
    container_name: php-lara-ecommerce
    entrypoint: /entrypoint.sh
    environment:
      CONTAINER_NAME: PHP
    #user: "1000:1000"
    volumes:
      - ./:/var/www/html
    expose:
      - "9000"
    networks:
      - network-lara-ecommerce
  horizon:
    build: docker/horizon-laravel
    container_name: horizon-lara-ecommerce
    entrypoint: dockerize -wait tcp://${DB_HOST}:3306 -timeout 60s /entrypoint.sh
    volumes:
      - ./:/var/www/html
    depends_on:
      - redis
    environment:
      CONTAINER_NAME: HORIZON_LARAVEL
  mysql:
    image: mysql:8
    container_name: mysql-lara-ecommerce
    command: --innodb-use-native-aio=0
    restart: unless-stopped
    tty: true
    volumes:
      - .docker/mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER:     "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql-lara-ecommerce
    networks:
      - network-lara-ecommerce
  # mysql-test:
  #   image: mysql:8
  #   tmpfs: /var/lib/mysql
  #   container_name: mysql-teste-lara-ecommerce
  #   command: --innodb-use-native-aio=0
  #   environment:
  #     MYSQL_DATABASE: "${DB_DATABASE}"
  #     MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
  #     SERVICE_TAGS: dev
  #     SERVICE_NAME: mysql-teste-lara-ecommerce
  #   networks:
  #     - network-lara-ecommerce
  phpmyadmin:
    build: docker/phpmyadmin
    container_name: phpmyadmin-lara-ecommerce
    environment:
      PMA_ARBITRARY: 1
    ports:
      - "8080:80"
    volumes:
      - .docker/phpmyadmin/data/sessions:/sessions
    networks:
      - network-lara-ecommerce
  redis:
    image: redis:alpine3.11
    container_name: redis-lara-ecommerce
    expose:
      - 6379
    ports:
      - "6379:6379"
    networks:
      - network-lara-ecommerce
